GET http://localhost:3001/api/

###
GET http://localhost:3001/api/640dfaba93d03b6a45f8ee85

###

PUT  http://localhost:3001/api/complete/640f3a63d830e982dc6da8e5

###


POST  http://localhost:3001/api/
Content-Type: application/json

{
      "name":"BusIk",
      "date":"12.10.2023 10:00",
      "phoneNumber": "09900746532",
      "directionOut": "Kyiv",
      "directionIn": "Lviv"
}
####

PUT http://localhost:3001/api/640e0c0594ac63481f9602ee
Content-Type: application/json

{
      "name": "Abrakadabra",
      "date":"12.10.2023 10:00",
      "phoneNumber": "7945745532",
      "directionOut": "Kyiv",
      "directionIn": "Lviv"
}
###
DELETE  http://localhost:3001/api/640cfa0661263fa1c3daa5b7

